In [11]:
from qdrant_client import QdrantClient
from qdrant_client.models import VectorParams, Distance, PayloadSchemaType, PointStruct, SparseVectorParams, Document,Prefetch, FusionQuery
from qdrant_client import models

import pandas as pd
import openai
import fastembed

In [12]:
qdrant_client = QdrantClient("http://localhost:6333")

In [13]:
qdrant_client.create_collection(
    collection_name="Amazon_Electronics_Products",
    vectors_config={
        "text-embedding-3-small": VectorParams(
            size=1536,
            distance=Distance.COSINE
        )
    },
    sparse_vectors_config={
        "bm25": SparseVectorParams(
            modifier=models.Modifier.IDF
        )
    }
)

True

In [15]:
qdrant_client.create_payload_index(
    collection_name="Amazon_Electronics_Products",
    field_name="store",
    field_schema=PayloadSchemaType.KEYWORD
)

UpdateResult(operation_id=2, status=<UpdateStatus.COMPLETED: 'completed'>)

In [65]:
import os
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Retrieve API keys from environment variables
openai_api_key = os.getenv('OPENAI_API_KEY')
google_api_key = os.getenv('GEMINI_API_KEY')
qdrant_url = os.getenv('QDRANT_URL')
qdrant_api_key = os.getenv('QDRANT_API_KEY')
langsmith_api_key = os.getenv('LANGSMITH_API_KEY')
if qdrant_url and "qdrant:6333" in qdrant_url:
    # Docker service host is not resolvable from a local notebook kernel
    qdrant_url = qdrant_url.replace("qdrant:6333", "localhost:6333")

# Verify keys are loaded
print(f"OpenAI API Key present: {bool(openai_api_key)}")
print(f"Google API Key present: {bool(google_api_key)}")
print(f"Qdrant URL present: {bool(qdrant_url)}")
print(f"Qdrant API Key present: {bool(qdrant_api_key)}")
print(f"Langsmith API Key present: {bool(langsmith_api_key)}")

OpenAI API Key present: True
Google API Key present: False
Qdrant URL present: True
Qdrant API Key present: False
Langsmith API Key present: True

In [16]:
def get_embedding(text, model= "text-embedding-3-small"):
    response = openai.embeddings.create(
        input=text,
        model=model
    )
    return response.data[0].embedding

In [17]:
def get_embeddings_batch(text_list, model= "text-embedding-3-small", batch_size=100):
    if(len(text_list) <= batch_size):
        response = openai.embeddings.create(input=text_list, model=model)
        return [embedding.embedding for embedding in response.data]
    all_embeddings = []
    counter = 1
    for i in range(0, len(text_list), batch_size):
        batch = text_list[i:i+batch_size]
        response = openai.embeddings.create(input=batch, model=model)
        all_embeddings.extend([embedding.embedding for embedding in response.data])
        print(f"Processed batch {counter} / {len(text_list) // batch_size + 1}")
        counter += 1
    return all_embeddings

In [ ]:
results = qdrant_client.query_points(
        collection_name="Amazon_Electronics_Data_Collection",
    )

In [20]:
df = pd.read_json('../../data/Data_With_Images.jsonl', lines=True)
print(df.head())

               main_category  \
0            All Electronics
1            All Electronics
2                  Computers
3             AMAZON FASHION
4  Cell Phones & Accessories

                                               title  average_rating  \
0             FS-1051 FATSHARK TELEPORTER V3 HEADSET             3.5
1                      Ce-H22B12-S1 4Kx2K Hdmi 4Port             5.0
2  Digi-Tatoo Decal Skin Compatible With MacBook ...             4.5
3  NotoCity Compatible with Vivoactive 4 band 22m...             4.5
4             Motorola Droid X Essentials Combo Pack             3.8

   rating_number                                           features  \
0              6                                                 []
1              1             [UPC: 662774021904, Weight: 0.600 lbs]
2            246  [WARNING: Please IDENTIFY MODEL NUMBER on the ...
3            233  [☛NotoCity 22mm band is designed for Vivoactiv...
4             64  [New Droid X Essentials Combo Pack, Exclusive ...

                                         description      price  \
0  [Teleporter V3 The “Teleporter V3” kit sets a ...  96.551146
1                               [HDMI In - HDMI Out]  96.551146
2                                                 []  19.990000
3                                                 []   9.990000
4  [all Genuine High Quality Motorola Made Access...  14.990000

                                              images  \
0  [{'thumb': 'https://m.media-amazon.com/images/...
1  [{'thumb': 'https://m.media-amazon.com/images/...
2  [{'thumb': 'https://m.media-amazon.com/images/...
3  [{'thumb': 'https://m.media-amazon.com/images/...
4  [{'thumb': 'https://m.media-amazon.com/images/...

                                              videos       store  \
0                                                 []   Fat Shark
1                                                 []        SIIG
2  [{'title': 'AL 2Sides Video', 'url': 'https://...  Digi-Tatoo
3                                                 []    NotoCity
4                                                 []     Verizon

                                          categories  \
0   [Electronics, Television & Video, Video Glasses]
1  [Electronics, Television & Video, Accessories,...
2  [Electronics, Computers & Accessories, Laptop ...
3  [Electronics, Wearable Technology, Clips, Arm ...
4  [Electronics, Computers & Accessories, Compute...

                                             details parent_asin  \
0  {'Date First Available': 'August 2, 2014', 'Ma...  B00MCW7G9M
1  {'Product Dimensions': '0.83 x 4.17 x 2.05 inc...  B00YT6XQSE
2  {'Brand': 'Digi-Tatoo', 'Color': 'Fresh Marble...  B07SM135LS
3  {'Date First Available': 'May 29, 2020', 'Manu...  B089CNGZCW
4  {'Product Dimensions': '11.6 x 6.9 x 3.1 inche...  B004E2Z88O

                             product_id
0  b86c3534-084b-449b-889e-50bd268ff964
1  945a8ca0-282f-424a-83db-646304822e23
2  c67b6305-54b3-4a14-816a-532c3d2a108c
3  5f511624-c19c-401e-8669-2d22afaa50dc
4  8b781665-d968-4aaf-ac18-f7e353de0de9

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2026 entries, 0 to 2025
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   main_category   2000 non-null   object
 1   title           2026 non-null   object
 2   average_rating  2026 non-null   float64
 3   rating_number   2026 non-null   int64
 4   features        2026 non-null   object
 5   description     2026 non-null   object
 6   price           2026 non-null   float64
 7   images          2026 non-null   object
 8   videos          2026 non-null   object
 9   store           2026 non-null   object
 10  categories      2026 non-null   object
 11  details         2026 non-null   object
 12  parent_asin     2026 non-null   object
 13  product_id      2026 non-null   object
dtypes: float64(2), int64(1), object(11)
memory usage: 221.7+ KB

In [22]:
len(df)

2026

In [219]:
def preprocess_description(row):
    return f"{row['title']} {row['description']} {row['main_category']} {row['features']} {row['price']} {row['categories']}"
    # return f"{row['categories']}"

In [220]:
def extract_first_large_images(row):
    return row['images'][0].get('large', None)

In [221]:
df['processed_description'] = df.apply(preprocess_description, axis=1)
df['image_url'] = df.apply(extract_first_large_images, axis=1)

In [222]:
df.head()

,main_category,title,average_rating,rating_number,features,description,price,images,videos,store,categories,details,parent_asin,product_id,processed_description,image_url
0,All Electronics,FS-1051 FATSHARK TELEPORTER V3 HEADSET,3.5,6,[],[Teleporter V3 The “Teleporter V3” kit sets a ...,96.551146,[{'thumb': 'https://m.media-amazon.com/images/...,[],Fat Shark,"[Electronics, Television & Video, Video Glasses]","{'Date First Available': 'August 2, 2014', 'Ma...",B00MCW7G9M,b86c3534-084b-449b-889e-50bd268ff964,FS-1051 FATSHARK TELEPORTER V3 HEADSET ['Telep...,https://m.media-amazon.com/images/I/41qrX56lsY...
1,All Electronics,Ce-H22B12-S1 4Kx2K Hdmi 4Port,5.0,1,"[UPC: 662774021904, Weight: 0.600 lbs]",[HDMI In - HDMI Out],96.551146,[{'thumb': 'https://m.media-amazon.com/images/...,[],SIIG,"[Electronics, Television & Video, Accessories,...",{'Product Dimensions': '0.83 x 4.17 x 2.05 inc...,B00YT6XQSE,945a8ca0-282f-424a-83db-646304822e23,Ce-H22B12-S1 4Kx2K Hdmi 4Port ['HDMI In - HDMI...,https://m.media-amazon.com/images/I/31OIMoOW70...
2,Computers,Digi-Tatoo Decal Skin Compatible With MacBook ...,4.5,246,[WARNING: Please IDENTIFY MODEL NUMBER on the ...,[],19.990000,[{'thumb': 'https://m.media-amazon.com/images/...,"[{'title': 'AL 2Sides Video', 'url': 'https://...",Digi-Tatoo,"[Electronics, Computers & Accessories, Laptop ...","{'Brand': 'Digi-Tatoo', 'Color': 'Fresh Marble...",B07SM135LS,c67b6305-54b3-4a14-816a-532c3d2a108c,Digi-Tatoo Decal Skin Compatible With MacBook ...,https://m.media-amazon.com/images/I/31t4bj9t88...
3,AMAZON FASHION,NotoCity Compatible with Vivoactive 4 band 22m...,4.5,233,[☛NotoCity 22mm band is designed for Vivoactiv...,[],9.990000,[{'thumb': 'https://m.media-amazon.com/images/...,[],NotoCity,"[Electronics, Wearable Technology, Clips, Arm ...","{'Date First Available': 'May 29, 2020', 'Manu...",B089CNGZCW,5f511624-c19c-401e-8669-2d22afaa50dc,NotoCity Compatible with Vivoactive 4 band 22m...,https://m.media-amazon.com/images/I/41j56fjX6S...
4,Cell Phones & Accessories,Motorola Droid X Essentials Combo Pack,3.8,64,"[New Droid X Essentials Combo Pack, Exclusive ...",[all Genuine High Quality Motorola Made Access...,14.990000,[{'thumb': 'https://m.media-amazon.com/images/...,[],Verizon,"[Electronics, Computers & Accessories, Compute...",{'Product Dimensions': '11.6 x 6.9 x 3.1 inche...,B004E2Z88O,8b781665-d968-4aaf-ac18-f7e353de0de9,Motorola Droid X Essentials Combo Pack ['all G...,https://m.media-amazon.com/images/I/51-DXSMlHa...

In [223]:
df.iloc[1]

main_category                                              All Electronics
title                                        Ce-H22B12-S1 4Kx2K Hdmi 4Port
average_rating                                                         5.0
rating_number                                                            1
features                            [UPC: 662774021904, Weight: 0.600 lbs]
description                                           [HDMI In - HDMI Out]
price                                                            96.551146
images                   [{'thumb': 'https://m.media-amazon.com/images/...
videos                                                                  []
store                                                                 SIIG
categories               [Electronics, Television & Video, Accessories,...
details                  {'Product Dimensions': '0.83 x 4.17 x 2.05 inc...
parent_asin                                                     B00YT6XQSE
product_id                            945a8ca0-282f-424a-83db-646304822e23
processed_description    Ce-H22B12-S1 4Kx2K Hdmi 4Port ['HDMI In - HDMI...
image_url                https://m.media-amazon.com/images/I/31OIMoOW70...
Name: 1, dtype: object

In [224]:
print(df.iloc[1]['processed_description'])

Ce-H22B12-S1 4Kx2K Hdmi 4Port ['HDMI In - HDMI Out'] All Electronics ['UPC: 662774021904', 'Weight: 0.600 lbs'] 96.5511458333 ['Electronics', 'Television & Video', 'Accessories', 'Cables', 'HDMI Cables']

In [225]:
print(df.iloc[1]['image_url'])

https://m.media-amazon.com/images/I/31OIMoOW70L._AC_.jpg

In [226]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2026 entries, 0 to 2025
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   main_category          2000 non-null   object
 1   title                  2026 non-null   object
 2   average_rating         2026 non-null   float64
 3   rating_number          2026 non-null   int64
 4   features               2026 non-null   object
 5   description            2026 non-null   object
 6   price                  2026 non-null   float64
 7   images                 2026 non-null   object
 8   videos                 2026 non-null   object
 9   store                  2026 non-null   object
 10  categories             2026 non-null   object
 11  details                2026 non-null   object
 12  parent_asin            2026 non-null   object
 13  product_id             2026 non-null   object
 14  processed_description  2026 non-null   object
 15  image_url              2026 non-null   object
dtypes: float64(2), int64(1), object(13)
memory usage: 253.4+ KB

In [227]:
data_to_embed = df[["processed_description", "image_url", "average_rating", "rating_number", "price", "parent_asin"]]

In [228]:
data_to_embed

,processed_description,image_url,average_rating,rating_number,price,parent_asin
0,FS-1051 FATSHARK TELEPORTER V3 HEADSET ['Telep...,https://m.media-amazon.com/images/I/41qrX56lsY...,3.5,6,96.551146,B00MCW7G9M
1,Ce-H22B12-S1 4Kx2K Hdmi 4Port ['HDMI In - HDMI...,https://m.media-amazon.com/images/I/31OIMoOW70...,5.0,1,96.551146,B00YT6XQSE
2,Digi-Tatoo Decal Skin Compatible With MacBook ...,https://m.media-amazon.com/images/I/31t4bj9t88...,4.5,246,19.990000,B07SM135LS
3,NotoCity Compatible with Vivoactive 4 band 22m...,https://m.media-amazon.com/images/I/41j56fjX6S...,4.5,233,9.990000,B089CNGZCW
4,Motorola Droid X Essentials Combo Pack ['all G...,https://m.media-amazon.com/images/I/51-DXSMlHa...,3.8,64,14.990000,B004E2Z88O
...,...,...,...,...,...,...
2021,"(2 Packs) 32mm 1/4"" to 3/8"" inch Male to Male ...",https://m.media-amazon.com/images/I/31ARI5oc4j...,3.6,7,96.551146,B00OPYMI2A
2022,i-BLASON Auto Sleep/Wake Google Nexus 10 inch ...,https://m.media-amazon.com/images/I/51C5pgZDJA...,3.8,157,96.551146,B00A1PM340
2023,Charger for Lenovo Laptop Computer 65W 45W USB...,https://m.media-amazon.com/images/I/41hZ69SRkT...,4.6,350,19.320000,B08L4YB3QC
2024,"Samsung XE550C22 - 12.1"" Series 5 Chromebook, ...",https://m.media-amazon.com/images/I/41ZuLno8a0...,2.3,4,96.551146,B07BHQPXXZ
2025,"Samsung AD44-00151A ADAPTOR;AA-MA9/XAA,A ['Sam...",https://m.media-amazon.com/images/I/41AkilV8su...,3.6,33,96.551146,B0036AZ2AO

In [229]:
text_to_embed = data_to_embed["processed_description"].tolist()

In [230]:
text_to_embed

["FS-1051 FATSHARK TELEPORTER V3 HEADSET ['Teleporter V3 The “Teleporter V3” kit sets a new level of value in the FPV world with Fat Shark renowned performance and quality. The fun of FPV is experienced firsthand through the large screen FPV headset with integrated NexwaveRF receiver technology while simultaneously recording onboard HD footage with the included “PilotHD” camera. The “Teleporter V3” kit comes complete with everything you need to step into the cockpit of your FPV vehicle. We’ve included our powerful 250mW 5.8Ghz transmitter, 25 degree FOV headset (largest QVGA display available), the brand new “PilotHD” camera with live AV out and all the cables, antennas and connectors needed.'] All Electronics [] 96.5511458333 ['Electronics', 'Television & Video', 'Video Glasses']",
 "Ce-H22B12-S1 4Kx2K Hdmi 4Port ['HDMI In - HDMI Out'] All Electronics ['UPC: 662774021904', 'Weight: 0.600 lbs'] 96.5511458333 ['Electronics', 'Television & Video', 'Accessories', 'Cables', 'HDMI Cables']",
 'Digi-Tatoo Decal Skin Compatible With MacBook Pro 13 inch (Model A2338/ A2289/ A2251) - Protective and Decorative Full Body Laptop Skin Decal Sticker, Anti-Scratch Vinly Skin Sticker Wrap [Fresh Marble] [] Computers [\'WARNING: Please IDENTIFY MODEL NUMBER on the bottom of your Macbook. Only fits for model A2338/ A2289/ A2251 (Macbook Pro 13" w/ Touch Bar, 2022/2020 release).\', \'Extra Care Yet Not Bulky. Our skin is capable of protecting the surface of your Macbook from daily scratches, dust, oil, water and fingerprint. Your Macbook remains fresh some years later.\', \'Elegant Style. Our stylish design and printing tech give your Macbook a 360 degree decorative and impressive looking. Take it out and get tons of compliments.\', \'Easy Apply. Easy, bubble-free installation and goo-free removal. Installation guide is well documented in paper material and video format.\', \'100% SATISFACTION GUARANTEED. We use best vinyl material and printing technology and offer premium service. Full refund is guaranteed if you are not satisfied with our product.\'] 19.99 [\'Electronics\', \'Computers & Accessories\', \'Laptop Accessories\', \'Skins & Decals\', \'Decals\']',
 'NotoCity Compatible with Vivoactive 4 band 22mm Quick Release Silicone Bands/Garmin Darth Vader/First Avenger/Polar Vantage Smartwatch Sport Breathable Strap Replacement for Gear S3 Classic Watchband [] AMAZON FASHION [\'☛NotoCity 22mm band is designed for Vivoactive 4 / Samsung Gear S3 Classic / S3 Frontier / Gear Live / Samsung Galaxy Watch 46mm / Huawei Watch GT / Tickwatch Pro / S2 / E2 / Pebble Classic / Time / Time Steel / Pebble 2 (Not Pebble steel) / Other Watches with 22mm lugs.\', \'➹Wrist Size: Small size fits wrist: 6.49inches-8.46inches (165-215mm), Large size fits wrist: 7.28inches-9.25inches (185-235mm) ,Please measure your wrist and make sure the size before you purchase.\', "➹No Tool Needed: Quick Release Pin is easy to wear or remove. Bands made of high-quality soft Silicone material, Anti-sweat, soft and more comfortable to wear. Metal clasp locks onto your watch band interface precisely and securely, so it\'s not moving on the watch band.", \'➹Suitable for Many Occasions: Good for perspiration which is suitable for sports of various kinds. Such as, Running, Walking, Climbing, swimming, biking and others. Simple stripe design, suitable for daily life, study and work.\', "☎Any problem with the item you receive or any opinion, please don\'t hesitate to contact us, we will find the best solution to solve."] 9.99 [\'Electronics\', \'Wearable Technology\', \'Clips, Arm & Wristbands\']',
 "Motorola Droid X Essentials Combo Pack ['all Genuine High Quality Motorola Made Accessories, including Multimedia Station with HDMI technology, HDMI Cable and AC Wall Charger, Motorola Navigation / Music Vehicle Charging Mount Car Dock and Motorola 12v Vehicle Power Adapter Charger!'] Cell Phones & Accessories ['New Droid X Essentials Combo Pack', 'Exclusive Package Incredible Value Worth $145!!!', 'Includes all Genuine High Quality Motorola Made Accessories'] 14.99 ['Electronics', 'Computers & Accessories', 'Computer Accessories & Peripherals', 'Memory Cards', 'Micro SD Cards']",
 'Raymarine Wi-Fish DownVision Blackbox Sonar with Wi-Fi [\'Transform your smartphone into a powerful CHIRP DownVision sonar with the Wi-Fish wireless sonar. Simply download the free Wi-Fish app and connect to the Wi-Fish module using standard Wi-Fi and you will be streaming real time sonar right to your phone or tablet. The Wi-Fish app also lets you rewind and save sonar imagery for sharing with friends online instantly. iOS7 or higher or Android 4 or higher compatible.\'] Sports & Outdoors [\'Black box Wi-Fi CHIRP DownVision sonar module\', \'Connect with the free Wi-Fish mobile app for iOS and Android devices\', "Return to the location of favorite fishing spots using the Wi-Fish augmented reality mode and your phone\'s GPS", \'Pause, zoom, and rewind the sonar right on your phone; Save you favorite catch and share with friends online\', \'Award winning wide-spectrum CHIRP DownVision sonar technology for photo-like images, high-speed tracking, and better deep water resolution; Includes transom mount CHIRP transducer with temperature sensor\'] 96.5511458333 [\'Electronics\', \'Car & Vehicle Electronics\', \'Marine Electronics\', \'Fish Finders & Depth Finders\']',
 "QGHXO Band for Garmin Vivofit 4, Soft Silicone Replacement Watch Band Strap for Garmin Vivofit 4 Activity Tracker, Small, Large, Ten Colors (5PCS Bands-Girl, Large) ['Compatibility', 'Custom designed for your precious', 'Garmin Vivofit 4', 'Activity Tracker, this Garmin Watch Sport Band features a combination of functionality and style. Fit for', 'Garmin Vivofit 4', 'Activity Tracker ONLY. NOT for Garmin Vivofit 1/Garmin Vivofit 2/Garmin Vivofit 3.', 'Feature', 'Material: Silicone. NOTE: Replacement Bands Only! Small fits wrists with a circumference of 122-188mm.  Large fits wrists with a circumference of 148-215mm. Models for selection: For Garmin Vivofit 4 Activity Tracker Only. Contracted design style, with you life contracted and not simple.', 'Package Included', 'Soft Silicone Replacement Watch Band Strap for Garmin Vivofit 4 Activity Tracker (No Tracker)'] Cell Phones & Accessories ['Personalized Your Garmin Vivofit 4 Activity Tracker with this refined replacement wrist band', 'Small fits wrists with a circumference of 122-188mm. Large fits wrists with a circumference of 148-215mm', 'Easy and direct installation and removal. Replacement Bands Only! Garmin device NOT included', 'Garmin Vivofit 4 Buckle Bracelet. Never lose your Garmin Vivofit 4. Fix the tracker fall off problem', 'Soft silicone with smooth finish for a sporty look, metal parts made with high quality stainless steel'] 14.89 ['Electronics', 'Wearable Technology', 'Arm & Wristband Accessories']",
 "Protech iPhone 4 microscope 60X Lens with illumination Led ['This accessory will convert your iPhone 4 into a portable microscope, yes you read it right and its not a normal microscope it can magnify images upto 60X. Now you can have your own microscope in your bag. This amazing little microscope has a built-in LED light for better image quality. The microscope should be applied through proper case on the back of the iPhone. Once installed, you can use the microscope to view objects up to 60x magnifications.'] Industrial & Scientific ['iPhone 4 Microscope with White 2-LED and Detector LED', 'Magnification: 60X , Light weight and easy to carry.', 'Blue LED ( x1) and Bright LEDs for different objects.', 'LED with On/Off Switch , The LEDs are powered by 3 LR1130 Cell batteries.', 'Plug and Play, nothing to install'] 96.5511458333 ['Electronics', 'Camera & Photo', 'Binoculars & Scopes', 'Microscopes', 'USB Microscopes']",
 "MOSISO Plastic Hard Shell Case & Keyboard Cover Compatible MacBook Air 11 Inch (Models: A1370 & A1465), Transparent Black [] Computers [] 96.5511458333 ['Electronics', 'Headphones, Earbuds & Accessories', 'Adapters']",
 'Fishfinder, Depth Finder Poly Sun Cover for 3" - 4" Models - Protects Your Screen from Sun / Weather Damage [\'Affordable and convenient way to cover your sonar unit. Protects from the sun and repells rain/snow. (It is water resistant, not waterproof). Has drawstring on bottom for securing tightly. Oversize design to fit over cables.\'] None [\'Made of poly material\', \'Available in black\', \'Drawstring\', \'For 3-4 inch models\', \'Measures 9 inches (23cm) x 6" (115cm) x 3" (8cm)\'] 10.99 [\'Electronics\', \'Car & Vehicle Electronics\', \'Marine Electronics\', \'Fish Finders & Depth Finders\']',
 'Network Magic 4.0 [\'Product description\', \'You try to connect your computers and devices together to share a printer, files and maintain an internet connection, but find yourself wasting hours sorting through confusing dialog boxes. It is time to stop with the hassles and let Network Magic do the work for you! With Network Magic you can easily 1) connect, manage, and secure your network; 2) share printers and files between all of your computers; 3) monitor Internet use and web sites visited; 4) connect and repair your network and internet connection; and 5) Protect your files and personal information from unwanted intruders. Stay connected to your preferred network without wasting time trying to set up or a repair a connection. Network Magic automatically detects connection problems and attempts to fix them for you. Add devices with one simple click. Don\\x92t waste another minute sorting through confusing instructions and pop up messages. The network map immediately detects and illustrates every device on your network. View the current status and information of each device, enabling you to easily manage your entire network. Share printers with the click of a mouse be able to print from any computer to any printer in your home and office. Share files, music, and photos between all of your computers quickly and easily. Simply click Share and you can access it from any computer. Wireless and broadband protection keeps your personal files and bandwidth protected from unwanted intruders. Health and security alerts ensure your firewall and antivirus security measures are doing their job by scanning your network, alerting you to issues and helping you resolve them. Know how your devices, software, and Internet are being used. Receive a daily report for each computer showing web sites visited and software applications used.\', \'From the Manufacturer\', \'Home networking is hard, no doubt about it. But Network Magic makes it easy to do all the things you want to with the computers and devices in your home. Things like sharing printers and files across all your computers, monitoring Internet use, and repairing broken Internet connections. No more emailing files to yourself just to print them out, no more wondering about where your kids are surfing on the Internet, no more waiting around for "the repair guy" to fix your wireless Internet.\', \'Features:\', \'Print from any computer in your home\', \'Print from any computer in your home\', \'Share files between all your home computers--even Macs and PCs\', \'Share files between all your home computers--even Macs and PCs\', \'Monitor Internet use and Web sites visited for any computer in your home\', \'Monitor Internet use and Web sites visited for any computer in your home\', \'Pinpoint and repair Internet connection problems\', \'Pinpoint and repair Internet connection problems\', \'View a live map of your network\', \'View a live map of your network\', \'Protect your wireless network from intruders\', \'Protect your wireless network from intruders\'] Computers [\'Connect, Manage, and Secure Your Network\', \'Share printers and files between all of your computers\', \'Connect and repair your network and internet connection\', \'View a live map of network; protect wireless network from intruders\', \'Print from any computer; monitor Internet use and Web sites visited\'] 96.5511458333 [\'Electronics\', \'Computers & Accessories\', \'Networking Products\', \'Network Adapters\']',
 "Dock Audio Extender Adapter Converter Cable for iPod iPhone 4 4S iPhone 5 5S iPad, Samsung & Other Smart Phones [] Portable Audio & Accessories [] 96.5511458333 ['Electronics', 'Computers & Accessories', 'Tablet Accessories', 'Chargers & Adapters']",
 'NANW Bands Compatible with Fitbit Versa/Versa 2/Versa Lite Small Large, Soft Silicone Replacement Band for Versa/Versa 2, Air Hole Wristband Strap for Women Men [] Cell Phones & Accessories [\'Compatible Models --- This silicone bands is special designed for Fitbit Versa, Fitbit Versa Special Edition, Versa 2 and Versa Lite Edition Smartwach.\', \'Adjustable Sizes --- This versa / versa lite bands silicone comes with two size, Large size for 6.7"-8.9" (170mm-226mm) wrists, Small size for 5.5"-6.7" (140mm-170mm) wrists.\', \'Super Comfortable --- This versa bands for women fits great and is less grippy, as a very flexible band, it is very comfortable for exercising and for everyday wear.\', \'Wide Application --- The band for versa is great for outdoor sports, jogging, business, parties, shopping etc. it’s suitable for men, women, girls and boys.\', \'Premium Silicone --- This versa band is made with soft, durable silicone and hypoallergenic nickel free stainless steel, no faded. lightweight and safe for daily and nightly wear. It is also sweat, water resistant.\'] 96.5511458333 [\'Electronics\', \'Wearable Technology\', \'Arm & Wristband Accessories\']',
 'eForCity Leather Case with Stand for 7-Inch Samsung Galaxy Tab 2, White/Black Zebra (PSAMGLXTLC26) [\'Compatible With Samsung Galaxy Tab 2 P3100 7.0". Leather Case with Stand\'] Computers [\'Stop worrying about scratching your Samsung; Galaxy Tab 2 7.0 by getting this excellent carrying accessory today\', \'Leather case features smooth synthetic leather and heavy duty stitching to ensure the long life of your Samsung; Galaxy Tab 2 7.0 Features with auto-securing magnetic flap for the best combination of security and ease of use\', \'Leather case cover can be turned into a horizontal stand for the convenience of viewing slide shows or videos Unique design allows easy access to all buttons, controls and ports without having to remove the case\'] 96.5511458333 [\'Electronics\', \'Computers & Accessories\', \'Tablet Accessories\', \'Bags, Cases & Sleeves\', \'Cases\']',
 "Novelty Cute Cartoon USB 2.0 Flash Drive Data Storage Memory Stick Cartoon USB Stick Pendrive Gift (16GB, Camera Black) ['This is a special usb stick that make as a cute camera shape.It is fun that use it to store photos and videos you tade;Or as a surprising gift for photographers. The perfect small size USB memory stick comes with a beaded key chain,you can hang it on something to decorate the thing you want,such as keychain/bag. Made out of soft rubber,shockproof, drop-proof Allow to store all of homework,course files,photos,favorite music and film. No need drive,only plug in. Easy to read and read in high speed.  Package Included: 1x U Disk 1x Chain'] Computers ['♥Best Gift♥-Catoon shape design different from traditional USB Flash Drive,cute and novelty,cheer up the working day.Cute outside but work well.It will be an amazing gift for your kid,friends and even significant others', '♥ Easy to Use♥-No require for installing a driver.Only plug in and transfer all of your favorite music,applications,ringtones,pictures,images,ect', '♥ Fast & Safe♥-USB 2.0 ensures high read/write speed for file transfer between devices.Electronic storage media,anti-vibration, anti-electromagnetic interference,waterproof,Safely storage of your files', '♥Compatibility♥- Suitable in all USB 2.0 ports which is standard in computers Windows 98/98SE, Me/2000/XP, VISTA, 7; Mac: OS 9.0/ 10.0 or later; Linux: kernel 2.4 or later', '♥ Warranty♥- 100% New; All of our products will be tested by the most authoritative testing software H2test before shipping to ensure its function.And we provide with one year warranty.Contact us once you have any problem'] 8.98 ['Electronics', 'Computers & Accessories', 'Data Storage']",
 'KEiiD PC Computer Speaker Compact Bluetooth Stereo System with Aluminum Housing for Laptop Desktop PC Gaming Computers, Unique Touch Controller, Built-in Bluetooth 5.0 Receiver for Wireless Streaming [] All Electronics [\'Beautifully designed compact speakers with real Aluminum housings have a distinct, upscale appearance and full-range sound, including surprising bass. Suitable for use with all laptop/desktop computers. And with three input modes (PC, Bluetooth, and AUX) you can also enjoy music and sound from other devices too.\', "The unique Touch Controller puts everything within reach. Shift modes and EQ, adjust volume, or mute the speakers--it\'s all there with a simple touch. The controller even has a headphone jack and an extra AUX connector so you can connect smartphones, tablets, mp3 players, CD players, and so on if you prefer.", \'This compact system goes beyond typical computer speakers. Its built-in Bluetooth 5.0 receiver allows wireless music streaming too (in Bluetooth mode). You can even answer or reject incoming (or redial calls) with the touch controller and talk via the built-in microphone.\', \'Each high-quality, full-range speaker also drives two passive radiators resulting in rich sound and powerful bass. The built-in DSP sound optimization chip upgrades the sound even further. These speakers are small in size but big in sound performance.\', \'3 EQ options (Music, Movie, and Game) adjust the sound whether you are streaming music, watching a movie, or playing a game. Game EQ mode includes 3D surround sound perfect for gaming. 1-year warranty & 24 hours after-sales support.\'] 96.5511458333 [\'Electronics\', \'Computers & Accessories\', \'Computer Accessories & Peripherals\', \'Audio & Video Accessories\', \'Computer Speakers\']',

In [231]:
embeddings = get_embeddings_batch(text_to_embed, batch_size=100)

Processed batch 1 / 21
Processed batch 2 / 21
Processed batch 3 / 21
Processed batch 4 / 21
Processed batch 5 / 21
Processed batch 6 / 21
Processed batch 7 / 21
Processed batch 8 / 21
Processed batch 9 / 21
Processed batch 10 / 21
Processed batch 11 / 21
Processed batch 12 / 21
Processed batch 13 / 21
Processed batch 14 / 21
Processed batch 15 / 21
Processed batch 16 / 21
Processed batch 17 / 21
Processed batch 18 / 21
Processed batch 19 / 21
Processed batch 20 / 21
Processed batch 21 / 21

In [232]:
len(embeddings)

2026

In [233]:
pointstructs = []
i = 1
for embedding, (_, data) in zip(embeddings, data_to_embed.iterrows()):
    pointstructs.append(
        PointStruct(
            id=i,
            vector={
                "text-embedding-3-small": embedding,
                "bm25": Document(
                    text=data['processed_description'],
                    model="qdrant/bm25",
                )
            },
            payload=data.to_dict()
        )
    )
    if i % 100 == 0:
        print(f"Prepared {i} / {len(embeddings)} points")
    i += 1

Prepared 100 / 2026 points
Prepared 200 / 2026 points
Prepared 300 / 2026 points
Prepared 400 / 2026 points
Prepared 500 / 2026 points
Prepared 600 / 2026 points
Prepared 700 / 2026 points
Prepared 800 / 2026 points
Prepared 900 / 2026 points
Prepared 1000 / 2026 points
Prepared 1100 / 2026 points
Prepared 1200 / 2026 points
Prepared 1300 / 2026 points
Prepared 1400 / 2026 points
Prepared 1500 / 2026 points
Prepared 1600 / 2026 points
Prepared 1700 / 2026 points
Prepared 1800 / 2026 points
Prepared 1900 / 2026 points
Prepared 2000 / 2026 points

In [234]:
print(pointstructs[0])

id=1 vector={'text-embedding-3-small': [-0.015716552734375, -0.015045166015625, 0.0202789306640625, -0.033233642578125, -0.007572174072265625, -0.032806396484375, 0.041656494140625, 0.051666259765625, 0.03631591796875, -0.0052947998046875, 0.02001953125, 0.0016756057739257812, -0.026275634765625, -0.0101470947265625, 0.00656890869140625, -0.02655029296875, -0.004787445068359375, -0.03009033203125, -0.040863037109375, 0.030914306640625, 0.0357666015625, -0.01226806640625, 0.00150299072265625, -0.0082855224609375, -0.017059326171875, -0.07415771484375, 0.0093841552734375, 0.033538818359375, 0.002765655517578125, 0.0019779205322265625, -0.0027637481689453125, -0.038299560546875, 0.024169921875, -0.0018949508666992188, -0.0374755859375, -0.0252532958984375, -0.00426483154296875, 0.0028171539306640625, -0.047760009765625, -0.0022258758544921875, 0.06573486328125, -0.0247344970703125, -0.0013103485107421875, -0.0049285888671875, 0.016265869140625, -0.0183258056640625, 0.027923583984375, 0.0018787384033203125, -0.057037353515625, 0.031463623046875, 0.0214080810546875, 0.0252838134765625, -0.057769775390625, 0.0924072265625, 0.023681640625, 0.0213470458984375, -0.0135955810546875, -0.01288604736328125, 0.01070404052734375, 0.0299224853515625, -0.032318115234375, -0.035186767578125, 0.0301971435546875, 0.040130615234375, 0.0019588470458984375, -0.00859832763671875, -0.060638427734375, 0.030364990234375, -0.050537109375, 0.02679443359375, -0.00531768798828125, 0.0195770263671875, -0.01383209228515625, -0.043609619140625, 0.0022525787353515625, 0.0251312255859375, -0.039947509765625, 0.008331298828125, -0.00896453857421875, -0.042236328125, -0.048248291015625, -0.007411956787109375, -0.04296875, -0.01233673095703125, -0.044677734375, -0.0172119140625, -0.0281982421875, -0.0282440185546875, -0.040679931640625, 0.0283660888671875, 0.003498077392578125, -0.0275115966796875, 0.0234527587890625, 0.029205322265625, -0.0168914794921875, -0.0175933837890625, -0.0238189697265625, -0.032867431640625, 0.006824493408203125, -0.006549835205078125, 0.0648193359375, -0.0013494491577148438, -0.0513916015625, -0.020477294921875, 0.031524658203125, 0.0182342529296875, -0.0227203369140625, -0.00434112548828125, 0.026336669921875, 0.057098388671875, -0.03338623046875, -0.02923583984375, 0.00841522216796875, 0.03936767578125, -0.043212890625, 0.032196044921875, 0.024627685546875, -0.06256103515625, 0.06072998046875, 0.00962066650390625, -0.0380859375, 0.0411376953125, 0.0234375, -0.034942626953125, 0.052337646484375, 0.01812744140625, -0.03338623046875, -0.0263671875, -0.0204620361328125, -0.0240020751953125, 0.056304931640625, -0.034912109375, 0.028656005859375, -0.024444580078125, 0.0144805908203125, 0.006809234619140625, -0.0394287109375, -0.018341064453125, -0.0214996337890625, -0.010528564453125, -0.0242462158203125, -0.003086090087890625, 0.03997802734375, -0.042877197265625, 0.021575927734375, 0.007350921630859375, -0.00539398193359375, -0.0143280029296875, 0.00801849365234375, 0.021453857421875, -0.047943115234375, -0.00881195068359375, -0.047454833984375, -0.0173492431640625, 4.082918167114258e-05, 0.0120697021484375, 0.050933837890625, 0.020111083984375, -0.0386962890625, -0.0232086181640625, -0.054412841796875, -0.00693511962890625, -0.0170745849609375, 0.00634002685546875, -0.00811004638671875, 0.032012939453125, 0.01143646240234375, -0.005786895751953125, -0.11181640625, -0.0210418701171875, -0.01076507568359375, -0.0146636962890625, -0.0640869140625, 0.00232696533203125, 0.02978515625, 0.0110626220703125, 0.05645751953125, -0.0218048095703125, -0.052093505859375, -0.043670654296875, -0.02642822265625, 0.02313232421875, 0.000957489013671875, -0.0031528472900390625, -0.0250701904296875, 0.0027523040771484375, 0.025421142578125, 0.00018644332885742188, 0.006870269775390625, -0.003559112548828125, 0.01497650146484375, 0.0209197998046875, -0.0311431884765625, 0.0214080810546875, 0.017669677734375, -0.004669189453125, -0.00638580322265625, 0.016845703125, 0.05926513671875, -0.031402587890625, -0.0006856918334960938, 0.0191192626953125, 0.03497314453125, -0.0206756591796875, -0.00812530517578125, -0.054412841796875, 0.00203704833984375, 0.046783447265625, 0.0672607421875, 0.004184722900390625, 0.03271484375, 0.018341064453125, 0.01275634765625, -0.015045166015625, -0.0487060546875, 0.06292724609375, -0.0120086669921875, 0.0164031982421875, 0.015777587890625, 0.0171356201171875, -0.053466796875, 0.0009741783142089844, 0.0254364013671875, -0.0419921875, -0.03375244140625, -0.0003781318664550781, 0.0193634033203125, 0.0006928443908691406, -0.0010938644409179688, -0.018463134765625, -0.0235595703125, 0.057159423828125, -0.0228118896484375, 0.00013053417205810547, 0.003185272216796875, -0.0225830078125, -0.0153656005859375, -0.06988525390625, -0.0012331008911132812, -0.014923095703125, -0.0086517333984375, 0.040313720703125, 0.01439666748046875, 0.0003333091735839844, 0.01432037353515625, -0.03192138671875, 0.01776123046875, -0.044830322265625, 0.0173492431640625, 0.0115509033203125, 0.068603515625, 0.044708251953125, -0.01256561279296875, 0.002384185791015625, 0.0308074951171875, 0.01026153564453125, -0.044891357421875, -0.0219879150390625, 0.0058441162109375, -0.0003135204315185547, 0.0154571533203125, -0.0115814208984375, -0.00814056396484375, 0.0361328125, -0.0147857666015625, -0.033111572265625, -0.00522613525390625, -0.041656494140625, -0.044464111328125, 0.03900146484375, 0.028656005859375, 0.032928466796875, 0.0243988037109375, 0.0645751953125, -0.0278167724609375, 0.026947021484375, 0.0364990234375, -0.03863525390625, 0.0164642333984375, 0.00270843505859375, -0.0251922607421875, 0.00501251220703125, -0.0171356201171875, -0.01264190673828125, -0.031585693359375, 0.0131072998046875, 0.06805419921875, 0.00437164306640625, -0.01425933837890625, -0.011566162109375, 0.062744140625, 0.007171630859375, -0.010467529296875, -0.037261962890625, 0.051361083984375, 0.0225982666015625, 0.0002956390380859375, 0.02691650390625, -0.012725830078125, -0.037445068359375, 0.0266265869140625, 0.006603240966796875, -0.0113067626953125, 0.0084381103515625, -0.03143310546875, 0.06146240234375, 0.031402587890625, 0.042694091796875, -0.07281494140625, -0.0265655517578125, -0.01296234130859375, -0.01442718505859375, -0.0380859375, -0.032806396484375, 0.029541015625, -0.0244293212890625, -0.03765869140625, -0.00933074951171875, 0.0039520263671875, -0.005413055419921875, 0.00362396240234375, -0.0313720703125, 0.0105438232421875, -0.015869140625, 0.042999267578125, -0.034515380859375, -0.0108795166015625, -0.016357421875, -0.0087738037109375, 0.01343536376953125, -0.01244354248046875, -0.0179443359375, -0.039581298828125, -0.0948486328125, -0.0404052734375, -0.051361083984375, -0.025360107421875, -0.02484130859375, -0.0438232421875, -0.01812744140625, 0.0304718017578125, 0.004688262939453125, -0.058929443359375, 0.011871337890625, -0.0350341796875, 0.07061767578125, 0.03533935546875, -0.003597259521484375, 0.0059814453125, 0.0662841796875, -0.024993896484375, 0.01031494140625, 0.0428466796875, -0.046173095703125, 0.018798828125, -0.05181884765625, 0.0390625, -0.0108184814453125, -0.04766845703125, 0.029296875, -0.0183258056640625, 0.056396484375, -0.0007886886596679688, 0.0091094970703125, 0.00428009033203125, 0.0134124755859375, -0.038360595703125, 0.00820159912109375, -0.057769775390625, -0.0234527587890625, 0.00745391845703125, 0.0182342529296875, 0.0291595458984375, 0.0032367706298828125, -0.041961669921875, -0.0775146484375, 0.04583740234375, -0.009674072265625, -0.0362548828125, 0.0232391357421875, 0.01258087158203125, -0.04541015625, -0.03094482421875, -0.01454925537109375, -0.017913818359375, 0.0067901611328125, -0.016937255859375, -0.01363372802734375, -0.036956787109375, -0.02978515625, -0.006923675537109375, -0.0293426513671875, -0.00867462158203125, -0.019775390625, 0.028961181640625, -0.00238037109375, 0.05023193359375, 0.038787841796875, 0.016204833984375, 0.02978515625, 0.037567138671875, 0.005268096923828125, -0.0233001708984375, -0.026947021484375, -0.00476837158203125, -0.004543304443359375, 0.0117950439453125, -0.0006155967712402344, 0.0177154541015625, -0.044830322265625, 0.0299835205078125, -0.09075927734375, 0.045623779296875, 0.03582763671875, 0.01409912109375, 0.0277099609375, -0.00943756103515625, -0.055023193359375, -0.0176544189453125, 0.003383636474609375, 0.0210723876953125, -0.00909423828125, -0.10400390625, 0.0225982666015625, -0.01245880126953125, 0.030609130859375, -0.0027923583984375, -0.022918701171875, 0.0252838134765625, -0.05377197265625, -0.04071044921875, -0.0077972412109375, 0.0185546875, 0.0269775390625, -0.0011081695556640625, 0.004543304443359375, -0.0307769775390625, -0.00592041015625, -0.060943603515625, 0.03436279296875, 0.0214080810546875, 0.0293426513671875, -0.016571044921875, -0.0171356201171875, -0.03155517578125, -0.0140838623046875, -0.01934814453125, 0.06463623046875, -0.028076171875, 0.00809478759765625, 0.023162841796875, -0.00641632080078125, -0.0150909423828125, 0.03631591796875, -0.01459503173828125, -0.0198211669921875, 0.035003662109375, 0.0087127685546875, -0.0266265869140625, -0.0017795562744140625, -0.0088348388671875, -0.0163421630859375, -0.0264129638671875, -0.03265380859375, 0.027008056640625, -0.01123809814453125, 0.0251007080078125, 0.00035309791564941406, -0.01003265380859375, -0.0009083747863769531, -0.00732421875, -0.01280975341796875, -0.01079559326171875, -0.002307891845703125, -0.0106048583984375, -0.009124755859375, 0.017181396484375, -0.0147857666015625, -0.0118560791015625, -0.0243988037109375, -0.009613037109375, -0.023895263671875, -0.0655517578125, 0.01291656494140625, -0.0162811279296875, 0.0751953125, 0.0288543701171875, -0.01396942138671875, -0.06744384765625, -0.058868408203125, -0.0056610107421875, -0.0269317626953125, -0.0056304931640625, -0.01690673828125, -0.01407623291015625, -0.0246124267578125, -0.045654296875, 0.003772735595703125, -0.027740478515625, 0.0305023193359375, 0.032196044921875, -0.0019321441650390625, 0.0080718994140625, 0.0028171539306640625, 0.045379638671875, 0.028656005859375, 0.0261993408203125, 0.00457763671875, -0.06402587890625, 0.01367950439453125, -0.01203155517578125, 0.0026760101318359375, -0.0051422119140625, 0.0187225341796875, -0.019317626953125, -0.0004711151123046875, 0.0083770751953125, 0.043212890625, 0.023956298828125, -0.0115966796875, -0.00931549072265625, -0.011688232421875, -0.0001302957534790039, -0.0191192626953125, -0.0224151611328125, -0.007358551025390625, -0.0157470703125, -0.088134765625, -0.020477294921875, -0.027435302734375, -0.018798828125, -0.0084228515625, -0.05072021484375, -0.046844482421875, -0.0499267578125, 0.0177001953125, -0.010589599609375, -0.00556182861328125, -0.0200042724609375, 0.021697998046875, 0.006160736083984375, 0.03326416015625, 0.00037360191345214844, 0.001617431640625, 0.00539398193359375, -0.00792694091796875, -0.024200439453125, -0.007564544677734375, 0.004367828369140625, -0.031219482421875, 0.006587982177734375, -0.031280517578125, -0.022705078125, -0.032928466796875, 0.006610870361328125, 0.0232391357421875, -0.0011816024780273438, -0.04156494140625, 0.002971649169921875, 0.0034618377685546875, 0.015869140625, 0.003505706787109375, -0.007160186767578125, 0.03857421875, 0.0138092041015625, 0.0229949951171875, -0.0023288726806640625, 0.00275421142578125, -0.01776123046875, -0.0245513916015625, 0.0023288726806640625, -0.037078857421875, 0.0169525146484375, -0.0248565673828125, -0.0040435791015625, 0.01971435546875, -0.0260009765625, -0.010162353515625, -0.0156402587890625, 0.0202484130859375, 0.0222930908203125, -0.006893157958984375, 0.0161285400390625, -0.0198974609375, 0.033050537109375, -0.021881103515625, -0.006458282470703125, -0.0031948089599609375, -0.0158233642578125, 0.0045928955078125, 0.01446533203125, -0.016876220703125, -0.043731689453125, 0.0269775390625, -0.0173797607421875, 0.0007281303405761719, 0.01229095458984375, -0.001964569091796875, 0.02685546875, -0.0164642333984375, -0.017974853515625, -0.0296478271484375, 0.006435394287109375, 0.007640838623046875, -0.0266265869140625, -0.03228759765625, 0.0308990478515625, -0.046905517578125, -0.00487518310546875, 0.035491943359375, 0.04150390625, 0.033843994140625, -0.0288543701171875, -0.03363037109375, -0.043853759765625, -0.024749755859375, 0.00960540771484375, -0.0046234130859375, 0.019805908203125, 0.0013580322265625, -0.04736328125, -0.01384735107421875, 0.0513916015625, 0.0148162841796875, -0.01380157470703125, 0.02783203125, 0.0084228515625, -0.031707763671875, -0.0203857421875, -0.046539306640625, -0.0106048583984375, 0.0091400146484375, 0.0275726318359375, -0.00739288330078125, -0.035247802734375, -0.0118408203125, 0.02410888671875, 0.036895751953125, 0.0081634521484375, -0.02197265625, 0.03387451171875, 0.038604736328125, 0.02960205078125, -0.0296478271484375, 0.032379150390625, 0.02899169921875, -0.05078125, -0.004886627197265625, 0.00753021240234375, -0.00814056396484375, -0.01538848876953125, -0.0055084228515625, 0.0115203857421875, 0.0005478858947753906, 0.034332275390625, 0.0171051025390625, -0.0333251953125, 0.045928955078125, 0.021697998046875, -0.0190887451171875, -0.0236968994140625, 0.017913818359375, -0.0041351318359375, 0.00533294677734375, 0.0016326904296875, -0.00396728515625, 0.01160430908203125, 0.005706787109375, -0.0302276611328125, -0.0168609619140625, -0.0134429931640625, -0.0165863037109375, -0.009796142578125, -0.0116119384765625, 0.0206451416015625, -0.01085662841796875, 0.03961181640625, -0.0118255615234375, 0.0293731689453125, 0.052734375, 0.01497650146484375, -0.0024929046630859375, -0.061553955078125, -0.01428985595703125, 0.00406646728515625, -0.006683349609375, -0.05126953125, -0.030059814453125, -0.01197052001953125, -0.00609588623046875, -0.0308685302734375, 0.0081787109375, -0.026123046875, 0.0103607177734375, -0.0019445419311523438, -0.02532958984375, -0.002101898193359375, 0.005901336669921875, -0.0076751708984375, -0.048980712890625, -0.0010585784912109375, 0.0030517578125, 0.00362396240234375, -0.048370361328125, -0.03411865234375, -0.0450439453125, -0.0224456787109375, 0.055206298828125, 0.032012939453125, -0.0068359375, -0.0460205078125, 0.018157958984375, -0.0213623046875, -0.004955291748046875, 0.0129852294921875, 0.042327880859375, -0.043914794921875, 0.01309967041015625, 0.0423583984375, 0.0032634735107421875, -0.003070831298828125, 0.051788330078125, 0.0016851425170898438, -0.00846099853515625, -0.003650665283203125, -0.005023956298828125, -0.045013427734375, -0.0097503662109375, 0.002689361572265625, 0.0004057884216308594, 0.01213836669921875, -0.0084381103515625, -0.0143280029296875, 0.004543304443359375, -0.01373291015625, 0.01412200927734375, -0.05694580078125, -0.047149658203125, -0.00595855712890625, -0.035430908203125, 0.004467010498046875, -0.01142120361328125, 0.032806396484375, 0.002788543701171875, -0.016448974609375, -0.0198974609375, 0.0222320556640625, -0.000453948974609375, -0.0024547576904296875, -0.041015625, -0.0106201171875, 0.01216888427734375, -0.0361328125, -0.01270294189453125, 0.015869140625, 0.006885528564453125, -0.00555419921875, 0.0135345458984375, 0.02490234375, -0.02484130859375, 0.017333984375, -0.029876708984375, -0.0076904296875, -9.626150131225586e-05, -0.0171051025390625, -1.6868114471435547e-05, -0.07281494140625, -0.029266357421875, -0.0311737060546875, 0.007965087890625, 0.0273284912109375, 0.005786895751953125, -0.03570556640625, 0.00893402099609375, 0.01036834716796875, 0.018341064453125, -0.03790283203125, 0.0416259765625, 0.0020885467529296875, -0.0168914794921875, -0.0211944580078125, -0.02642822265625, 0.041473388671875, 0.027435302734375, -0.010223388671875, 0.031768798828125, -0.0310516357421875, 0.027313232421875, 0.0090484619140625, -0.0165863037109375, 0.00511932373046875, -0.038787841796875, -0.0132598876953125, -0.01094818115234375, 0.017181396484375, 0.02008056640625, 0.0285797119140625, -0.068603515625, 0.0078125, 0.024200439453125, -0.0199127197265625, 0.0239410400390625, 0.018157958984375, 0.01497650146484375, 0.001262664794921875, 0.03387451171875, -0.01806640625, 0.02813720703125, 0.016632080078125, 0.002155303955078125, -0.005428314208984375, 0.0230712890625, -0.00012445449829101562, -0.0001176595687866211, 0.01372528076171875, 0.033447265625, 0.0016851425170898438, -0.046875, 0.014892578125, 0.019744873046875, 0.007762908935546875, -0.03533935546875, 0.03387451171875, -0.039031982421875, -0.0067596435546875, -0.00800323486328125, -0.00835418701171875, 0.029022216796875, -0.01213836669921875, -0.028472900390625, 0.030670166015625, -0.0064849853515625, 0.007442474365234375, -0.023162841796875, 0.036956787109375, 0.0198211669921875, -0.0046234130859375, 0.00936126708984375, -0.0234832763671875, -0.016510009765625, 0.020904541015625, -0.0127716064453125, -0.0052337646484375, -0.00586700439453125, 0.0302276611328125, 0.0169677734375, 0.0210418701171875, 0.02020263671875, -0.040740966796875, 0.022186279296875, 0.0006985664367675781, -0.01486968994140625, -0.0192108154296875, 0.01201629638671875, 0.01486968994140625, 0.0189361572265625, -0.00373077392578125, -0.00580596923828125, 0.01412200927734375, 0.0019273757934570312, -0.0791015625, -0.0277099609375, -0.00258636474609375, 0.001850128173828125, 0.003070831298828125, -0.004032135009765625, -0.0058746337890625, -0.00875091552734375, 0.0189056396484375, 0.01837158203125, 0.0214996337890625, 0.01233673095703125, 0.0002677440643310547, 0.00794219970703125, -0.03460693359375, 0.0323486328125, -0.002178192138671875, 0.024993896484375, -0.0260009765625, -0.0011157989501953125, -0.00904083251953125, 0.03955078125, 0.0435791015625, -0.003997802734375, -0.004058837890625, 0.043792724609375, -0.041107177734375, -0.003330230712890625, 0.00839996337890625, 0.0009522438049316406, -0.0010156631469726562, 0.02520751953125, 0.04107666015625, -0.0161895751953125, -0.02789306640625, 0.012725830078125, -0.00232696533203125, 0.073974609375, 0.008056640625, -0.0005917549133300781, -0.0654296875, -0.007171630859375, -0.0036067962646484375, -0.001880645751953125, 0.00759124755859375, 0.00853729248046875, -0.021331787109375, -0.024139404296875, -0.0126495361328125, 0.060302734375, 0.01432037353515625, -0.0016918182373046875, 0.027374267578125, -0.0005078315734863281, 0.0233001708984375, -0.0203094482421875, -0.02508544921875, 0.003143310546875, 0.033905029296875, 0.000392913818359375, 0.0247039794921875, -0.019805908203125, 0.0030384063720703125, -0.020660400390625, 0.0005917549133300781, 0.0064239501953125, -0.0035724639892578125, 0.0262603759765625, 0.0137176513671875, 0.007427215576171875, -0.018280029296875, 0.04248046875, 0.00501251220703125, 0.0036754608154296875, 0.02874755859375, -0.003627777099609375, 0.00852203369140625, -5.6684017181396484e-05, -0.004619598388671875, -0.013336181640625, 0.0159759521484375, -0.0182952880859375, 0.01233673095703125, 0.0187530517578125, 0.0548095703125, -0.0006871223449707031, 0.00814056396484375, 0.0242767333984375, 0.00933837890625, -0.0099945068359375, 0.00011134147644042969, 0.047271728515625, 0.040618896484375, 0.00687408447265625, 0.0119476318359375, -0.05810546875, 0.0345458984375, 0.02191162109375, -0.0016412734985351562, 0.033660888671875, -0.0149383544921875, 0.00341033935546875, 0.022857666015625, -0.029052734375, -0.01459503173828125, 0.007160186767578125, 0.020843505859375, 0.015167236328125, -0.01800537109375, 0.0235595703125, -0.040435791015625, -0.002330780029296875, 0.01313018798828125, -0.01507568359375, -0.0005221366882324219, -0.0012006759643554688, -0.01151275634765625, 0.0386962890625, 0.03997802734375, 0.027130126953125, 0.0126190185546875, 0.040679931640625, 0.004138946533203125, -0.008544921875, -0.01904296875, 0.0244598388671875, 0.0142364501953125, -0.034912109375, -0.0031566619873046875, 0.0026378631591796875, 0.00994110107421875, -0.0035343170166015625, -0.0007758140563964844, 0.0013751983642578125, -0.004085540771484375, -0.0157012939

In [235]:
batch_size = 128

for start in range(0, len(pointstructs), batch_size):
    batch = pointstructs[start:start + batch_size]
    qdrant_client.upsert(
        collection_name="Amazon_Electronics_Products",
        wait=True,
        points=batch,
    )

print(f"Upserted {len(pointstructs)} points in batches of {batch_size}.")

Upserted 2026 points in batches of 128.

Hybrid Retrieval

In [236]:
def retrieve_data(query, qdrant_client, top_k=5):
    query_embedding = get_embedding(query)
    search_result = qdrant_client.query_points(
        collection_name="Amazon_Electronics_Products",
        prefetch = [
            Prefetch(
            query = query_embedding,
            using= "text-embedding-3-small",
            limit = 20
           ),
           Prefetch(
            query = Document(text=query, model="qdrant/bm25"),
            using= "bm25",
            limit = 20
           )
        ],
        query=FusionQuery(fusion=models.Fusion.RRF),
        limit=top_k
    )

    retrieved_context_ids = []
    retrieved_contexts = []
    similarity_scores = []
    retrieved_context_ratings = []
    retrieved_context_prices = []
    retrieved_context_images = []
    retrieved_context_rating_numbers = []

    for result in search_result.points:
        retrieved_context_ids.append(result.payload['parent_asin'])
        retrieved_contexts.append(result.payload['processed_description'])
        similarity_scores.append(result.score)
        retrieved_context_ratings.append(result.payload['average_rating'])
        retrieved_context_prices.append(result.payload['price'])
        retrieved_context_images.append(result.payload['image_url'])
        retrieved_context_rating_numbers.append(result.payload['rating_number'])

    return {
        "retrieved_context_ids": retrieved_context_ids,
        "retrieved_contexts": retrieved_contexts,
        "similarity_scores": similarity_scores,
        "retrieved_context_ratings": retrieved_context_ratings,
        "retrieved_context_prices": retrieved_context_prices,
        "retrieved_context_images": retrieved_context_images,
        "retrieved_context_rating_numbers": retrieved_context_rating_numbers
    }

In [237]:
results = retrieve_data("Looking for a good quality wireless mouse with long battery life", qdrant_client, top_k=5)

In [238]:
results

{'retrieved_context_ids': ['B00113ZBYA',
  'B07R32PZZ6',
  'B0BWYJJLSF',
  'B071NFDHX3',
  'B00EYIRKE8'],
 'retrieved_contexts': ['Logitech V200 Cordless Mouse - Silver (931379-0403) [\'From the Manufacturer\', \'Maximize your productivity, where ever you are\\x97at your desk, on the road, or even in the conference room down the hall.\', \'The Logitech V200 Cordless Notebook Mouse is designed for the demanding mobile professional. Compact, with an unsurpassed battery life of up to one year, the V200 guarantees comfort and reliable performance on the road.\', "Its 2.4GHz digital cordless technology provides longer range compared to traditional wireless, and delivers interference-free operation. The 2.4GHz micro-receiver snaps into the mouse for easy transport and turns it off for power efficiency. Invisible Light optical tracking delivers smooth, precise control and the Tilt Wheel Plus Zoom makes side-to-side scrolling effortless. All of this is wrapped up in a durable design that\'s ideal for business-class mobility.", \'Tilt Wheel Plus Zoom. Scroll side-to-side and zoom in on page details.\', \'Tilt Wheel Plus Zoom.\', \'Scroll side-to-side and zoom in on page details.\', \'5X stronger wireless connection: Better range and less interference. 2.4GHz micro-receiver snaps into mouse for easy transport.\', \'5X stronger wireless connection:\', \'Better range and less interference. 2.4GHz micro-receiver snaps into mouse for easy transport.\', \'Keep on going for up to a year with super-long battery life.\', \'Keep on going for up to a year\', \'with super-long battery life.\', \'Take it with you. Durable design is ideal for business-class mobility.\', \'Take it with you.\', \'Durable design is ideal for business-class mobility.\', \'Track your movements accurately with precision optical performance.\', \'Track your movements accurately\', \'with precision optical performance.\'] All Electronics [\'Tilt wheel lets you scroll side-to-side and zoom in on page details\', \'Super-long battery life of up to one year keeps you going\', \'Durable design is ideal for business-class mobility\', \'5X stronger wireless connection means better range and less interference\', \'2.4GHz micro-receiver snaps into mouse for easy transport\'] 59.99 [\'Electronics\', \'Computers & Accessories\', \'Computer Accessories & Peripherals\', \'Keyboards, Mice & Accessories\', \'Mice\']',
  '2.4 GHz Wireless Mouse, Six-Button Silent Wireless Computer Mice with 1200/1600/2400 Adjustable Portable USB Mouse for Desktop/Laptop/PC(Gold) [\'Feature:\', \'W Optical interface type USB key number: 4 Optical resolution: 1600 DPI Ergonomics: supports LED mouse: blue LED light System clock: 250Hz Frame type: 3000 frames / sec. Maximum acceleration: 20g Ultra precise scroll wheel Customize DPI switch: 600/1200/1600 DPI Ultra-pretty and low-friction Resulution adjustable in driverless unit Switch life: 5 million cycles Special edition for games, built-in weight Optical technology works on most surfaces Smart connectivity No need to code, plug and play Compatible with Windows XP, Vista, Windows 7, Windows 8, ME, 2000, MAC\'] All Electronics [\'[Cool design] The appearance of the mouse is modeled by Iron Man. It is cool and stylish, ergonomically designed, and comfortable to touch. Your hands will not feel tired when using for a long time. As a gift to your family, friends are also a great choice.\', \'[Responsive] Wireless engineering optical mouse with 1600DPI high precision resolution for fast and sensitive response when connected to a laptop.\', "[Easy to connect] Simply connect to the computer\'s USB port using the configured USB receiver, no additional drivers, plug and play (note: the USB receiver is hidden in the battery compartment)", \'[Ultra-quiet design] The wireless gaming mouse has an ultra-quiet design that provides a more relaxing and enjoyable experience for your everyday use without worrying about affecting others around you.\', \'[Reliable quality & worry-free warranty] Quality materials and advanced optical sensors, reliable quality; fhong promises to provide you with a one-year free warranty. If you encounter any problems, you can contact us immediately through Amazon, we will be happy to serve you!\'] 15.99 [\'Electronics\', \'Computers & Accessories\', \'Computer Accessories & Peripherals\', \'Keyboards, Mice & Accessories\', \'Mice\']',
  'Wireless Keyboard and Mouse Combo, EDJO Full-Sized Ergonomic Computer Keyboard with Wrist Rest and 3 Level DPI Adjustable Wireless Mouse for Windows, Mac OS Desktop/Laptop/PC (White) [] All Electronics ["【ERGONOMIC WIRELESS KEYBOARD AND MOUSE COMBO】EDJO Full-sized wireless keyboard is ergonomically designed with Palm Rest and folding holder that can keep it at an optimum slope，prevent your wrists from hurting while long sessions of typing. Keyboard is also designed with anti-slide pads so it will stay in place when you\'re typing quickly. NOTE: THE USB RECEIVER IS INSERTED IN THE BATTERY COMPARTMENT OF THE MOUSE, YOU CAN FIND IT WHEN OPEN THE MOUSE BATTERY COVER.", \'【PLUG & PLAY 2.4G WIRELESS CONNECTION】One 2.4 GHz USB receiver can connect both the keyboard and mouse, can also be used separately, plug & play, no need to download any software. 2.4 GHz wireless provides a powerful and reliable connection up to 33 feet(10m) without any delays.\', \'【AUTOMATIC POWER SAVING FUNCTION】The EDJO wireless keyboard and mouse combo has the function of automatically entering the power-saving state. When you stop using the keyboard more than 30 minutes, stop using the mouse more than 25 seconds, they will enter sleep mode respectively to save power. This feature greatly extends the battery life, you can click any button to activity the device. The keyboard need 1 x AA battery, the mouse need 1 x AA battery. (Battery Not Included)\', \'【WIRELESS OPTICAL MOUSE】The mouse was optical design, even on some smooth surfaces, precise control can be obtained. 3-level adjustable DPI (800/1200/1600) allows you to choose your favorite moving speed of cursor. In addition, this wireless mouse is symmetry design, no matter you are Right handed Left handed, both hands are available, suitable for all people.\', \'【UNIVERSAL COMPATIBILITY & AFTER-SALES SERVICE】This wireless keyboard and mice combo compatible with windows XP/Vista/7/8/10/X, Mac and other operating system. Works well with desktops, Chrome-book, PC, Laptop, Computer and more. If you encounter any problems during use, please contact us via Amazon email, we will provide a satisfactory solution.\'] 34.99 [\'Electronics\', \'Computers & Accessories\', \'Computer Accessories & Peripherals\', \'Keyboards, Mice & Accessories\', \'Keyboard & Mouse Combos\']',
  "Logitech Doodle Collection M238 Mouse - Optical - Wireless - 3 Button(s) - Champion Coral ['Scroll to Your Happy Place. A doodle collection wireless mouse takes you far away from the everyday. Choose a distinct and colourful doodle design that expresses your creativity - from floating robot heads to skateboarding cheeseburgers. Plus, the wireless mouse comes with 15 playful and colourful stickers so you can extend your happy place to your laptop, phone and more. Lasts up to 12 months on a single battery. Responds up to 33 feet/10 m with a Nano receiver. Rips through web pages and docs with precision scrolling. Works with the operating systems you already use like Windows, Mac, Chrome OS and Linux. Small-sized so you can carry it with you.'] All Electronics [] 96.5511458333 ['Electronics', 'Computers & Accessories', 'Computer Accessories & Peripherals', 'Keyboards, Mice & Accessories', 'Mice']",
  "HDE Ultra-Thin Wireless Mouse 2.4GHZ Ergonomic Candy Colored Optical Mouse with USB Nano Receiver and Adjustable DPI Switch (White) ['Slim, comfortable, and responsive - this accessory is the sports car of computer mice. Operating on a 2.4 GHz wireless frequency, this mouse is made of lightweight yet durable ABS plastic, insuring a long life of providing you with optimal computer input. The optical sensor provides more responsive reaction than a normal laser mouse and the adjustable DPI can be set to your preferred level of sensitivity. Go fast, go sleek, and go slim with a slimmed down wireless mouse and leave all the others in the dust.'] Computers [] 96.5511458333 ['Electronics', 'Computers & Accessories', 'Computer Accessories & Peripherals', 'Keyboards, Mice & Accessories', 'Mice']"],
 'similarity_scores': [1.0, 0.5, 0.42424244, 0.41025642, 0.34285715],
 'retrieved_context_ratings': [3.6, 4.5, 4.3, 4.6, 3.4],
 'retrieved_context_prices': [59.99,
  15.99,
  34.99,
  96.5511458333,
  96.5511458333],
 'retrieved_context_images': ['https://m.media-amazon.com/images/I/41MHE015XXL._AC_.jpg',
  'https://m.media-amazon.com/images/I/31iBNqsEG+L._AC_.jpg',
  'https://m.media-amazon.com/images/I/31nBn57mOUL._AC_.jpg',
  'https://m.media-amazon.com/images/I/51FJPC7vNDL._AC_.jpg',
  'https://m.media-amazon.com/images/I/31p+bTjnT-L._AC_.jpg'],
 'retrieved_context_rating_numbers': [291, 480, 3862, 249, 266]}

In [239]:
results["retrieved_contexts"][0]

'Logitech V200 Cordless Mouse - Silver (931379-0403) [\'From the Manufacturer\', \'Maximize your productivity, where ever you are\\x97at your desk, on the road, or even in the conference room down the hall.\', \'The Logitech V200 Cordless Notebook Mouse is designed for the demanding mobile professional. Compact, with an unsurpassed battery life of up to one year, the V200 guarantees comfort and reliable performance on the road.\', "Its 2.4GHz digital cordless technology provides longer range compared to traditional wireless, and delivers interference-free operation. The 2.4GHz micro-receiver snaps into the mouse for easy transport and turns it off for power efficiency. Invisible Light optical tracking delivers smooth, precise control and the Tilt Wheel Plus Zoom makes side-to-side scrolling effortless. All of this is wrapped up in a durable design that\'s ideal for business-class mobility.", \'Tilt Wheel Plus Zoom. Scroll side-to-side and zoom in on page details.\', \'Tilt Wheel Plus Zoom.\', \'Scroll side-to-side and zoom in on page details.\', \'5X stronger wireless connection: Better range and less interference. 2.4GHz micro-receiver snaps into mouse for easy transport.\', \'5X stronger wireless connection:\', \'Better range and less interference. 2.4GHz micro-receiver snaps into mouse for easy transport.\', \'Keep on going for up to a year with super-long battery life.\', \'Keep on going for up to a year\', \'with super-long battery life.\', \'Take it with you. Durable design is ideal for business-class mobility.\', \'Take it with you.\', \'Durable design is ideal for business-class mobility.\', \'Track your movements accurately with precision optical performance.\', \'Track your movements accurately\', \'with precision optical performance.\'] All Electronics [\'Tilt wheel lets you scroll side-to-side and zoom in on page details\', \'Super-long battery life of up to one year keeps you going\', \'Durable design is ideal for business-class mobility\', \'5X stronger wireless connection means better range and less interference\', \'2.4GHz micro-receiver snaps into mouse for easy transport\'] 59.99 [\'Electronics\', \'Computers & Accessories\', \'Computer Accessories & Peripherals\', \'Keyboards, Mice & Accessories\', \'Mice\']'